//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string EMAIL_BODY_EMPLOYEE {
            get {
                return ResourceManager.GetString("EMAIL_BODY_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        internal static string EMAIL_BODY_END_DATE {
            get {
                return ResourceManager.GetString("EMAIL_BODY_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EMAIL_BODY_HOLIDAY_REQUEST_APPROVED {
            get {
                return ResourceManager.GetString("EMAIL_BODY_HOLIDAY_REQUEST_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected with the following reason: {0}.
        /// </summary>
        internal static string EMAIL_BODY_HOLIDAY_REQUEST_REJECTED {
            get {
                return ResourceManager.GetString("EMAIL_BODY_HOLIDAY_REQUEST_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        internal static string EMAIL_BODY_START_DATE {
            get {
                return ResourceManager.GetString("EMAIL_BODY_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Request.
        /// </summary>
        internal static string EMAIL_TITLE_HOLIDAY_REQUEST {
            get {
                return ResourceManager.GetString("EMAIL_TITLE_HOLIDAY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Request Approved.
        /// </summary>
        internal static string EMAIL_TITLE_HOLIDAY_REQUEST_APPROVED {
            get {
                return ResourceManager.GetString("EMAIL_TITLE_HOLIDAY_REQUEST_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Request Rejected.
        /// </summary>
        internal static string EMAIL_TITLE_HOLIDAY_REQUEST_REJECTED {
            get {
                return ResourceManager.GetString("EMAIL_TITLE_HOLIDAY_REQUEST_REJECTED", resourceCulture);
            }
        }
    }
}
